### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wall2in** [kcauchy/node-ctp#1]
system: win10
vs version: 2017

log:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Copying v6.3.6.000/win32/x64/thosttraderapi.lib to D:\github\node-ctp\bindings\build\Release\\thosttraderapi.lib
  已复制         1 个文件。
  Copying v6.3.6.000/win32/x64/thostmduserapi.lib to D:\github\node-ctp\bindings\build\Release\\thostmduserapi.lib
  已复制         1 个文件。
  Copying v6.3.6.000/win32/x64/thosttraderapi.dll to D:\github\node-ctp\bindings\build\Release\\thosttraderapi.dll
  已复制         1 个文件。
  Copying v6.3.6.000/win32/x64/error.xml to D:\github\node-ctp\bindings\build\Release\\error.xml
  已复制         1 个文件。
  Copying v6.3.6.000/win32/x64/error.dtd to D:\github\node-ctp\bindings\build\Release\\error.dtd
  已复制         1 个文件。
  Copying v6.3.6.000/win32/x64/thostmduserapi.dll to D:\github\node-ctp\bindings\build\Release\\thostmduserapi.dll
  已复制         1 个文件。
  CtpPrice.cc
  module.cpp
  GetObjectField.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1194: 无法延迟加载“node.exe”，原因在于数据符号“"__declspec(dllimport) const v8::ExternalOneByteStringResourceImpl::`vftable'" (__imp_??_7ExternalOneByteStringResourceImpl@v8@@6B@)”的导入；链接时不使用 /DELAYLOAD:node.exe [D:\git
hub\node-ctp\bindings\bu
ild\ctp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\finde\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\finde\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\github\node-ctp\bindings
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by kcauchy** [comment]
```
karl@DESKTOP-63HS1DG MINGW64 ~/Desktop/node-ctp/bindings (master)
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@8.1.2 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\.node-gyp_npminstall\\node_modules\\.3.6.1@node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\.node-gyp_npminstall\\node_modules\\.3.6.1@node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\.node-gyp\\8.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\karl\\.node-gyp\\8.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\.node-gyp_npminstall\\node_modules\\.3.6.1@node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\karl\\Desktop\\node-ctp\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\karl\Desktop\node-ctp\bindings\build\..\readerwritequeue.h
gyp info ok

karl@DESKTOP-63HS1DG MINGW64 ~/Desktop/node-ctp/bindings (master)
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@8.1.2 | win32 | x64
gyp info spawn F:\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying v6.3.6.000/win32/x64/thosttraderapi.lib to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\thosttraderapi.lib
          1 file(s) copied.
  Copying v6.3.6.000/win32/x64/thostmduserapi.lib to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\thostmduserapi.lib
          1 file(s) copied.
  Copying v6.3.6.000/win32/x64/thosttraderapi.dll to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\thosttraderapi.dll
          1 file(s) copied.
  Copying v6.3.6.000/win32/x64/error.xml to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\error.xml
          1 file(s) copied.
  Copying v6.3.6.000/win32/x64/error.dtd to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\error.dtd
          1 file(s) copied.
  Copying v6.3.6.000/win32/x64/thostmduserapi.dll to C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\thostmduserapi.dll
          1 file(s) copied.
  CtpPrice.cc
  module.cpp
  GetObjectField.cpp
  CtpModule.cpp
  CtpTrade.cc
  win_delay_load_hook.cc
     Creating library C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.lib and object C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.exp
  Generating code
  Finished generating code
  ctp.vcxproj -> C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\ctp.node
  ctp.vcxproj -> C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.pdb (Full PDB)
gyp info ok
```

**Comment by wall2in** [comment]
configure log:

`gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\finde\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\github\\node-ctp\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\finde\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\finde\\.node-gyp\\8.1.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\finde\\.node-gyp\\8.1.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\finde\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\finde\\.node-gyp\\8.1.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\github\\node-ctp\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\github\\node-ctp\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
D:\github\node-ctp\bindings\build\..\readerwritequeue.h
gyp info ok
`

**Comment by kcauchy** [comment]
```

PS C:\Users\karl\Desktop\node-ctp\bindings> node-gyp --version
v3.6.1
PS C:\Users\karl\Desktop\node-ctp\bindings> npm install node-gyp@3.6.2 -g
C:\Users\karl\AppData\Roaming\npm\node-gyp -> C:\Users\karl\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.6.2
added 89 packages, removed 117 packages and updated 14 packages in 11.628s
PS C:\Users\karl\Desktop\node-ctp\bindings> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.1.3/node-v8.1.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.1.3/node-v8.1.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.1.3/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.1.3/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v8.1.3/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v8.1.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.1.3/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v8.1.3/win-x86/node.lib
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\.node-gyp\\8.1.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\karl\\.node-gyp\\8.1.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\karl\\.node-gyp\\8.1.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\karl\\Desktop\\node-ctp\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\karl\Desktop\node-ctp\bindings\build\..\readerwritequeue.h
gyp info ok
PS C:\Users\karl\Desktop\node-ctp\bindings> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\karl\\.node-gyp\\8.1.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\karl\\.node-gyp\\8.1.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\karl\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\karl\\.node-gyp\\8.1.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\karl\\Desktop\\node-ctp\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\karl\\Desktop\\node-ctp\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\karl\Desktop\node-ctp\bindings\build\..\readerwritequeue.h
gyp info ok
PS C:\Users\karl\Desktop\node-ctp\bindings> node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp info spawn F:\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  CtpPrice.cc
  module.cpp
  GetObjectField.cpp
  CtpModule.cpp
  CtpTrade.cc
  win_delay_load_hook.cc
     Creating library C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.lib and object C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.exp
  Generating code
  Finished generating code
  ctp.vcxproj -> C:\Users\karl\Desktop\node-ctp\bindings\build\Release\\ctp.node
  ctp.vcxproj -> C:\Users\karl\Desktop\node-ctp\bindings\build\Release\ctp.pdb (Full PDB)
gyp info ok
PS C:\Users\karl\Desktop\node-ctp\bindings>
```

**Comment by kcauchy** [comment]
Still no problems for compiling under Windows 10, Node 8.1.3, node-gyp 3.6.2

**Comment by kcauchy** [comment]
[node-gyp.zip](https://github.com/kcauchy/node-ctp/files/1165844/node-gyp.zip)
